#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.

# Creates a symbolic lin (-s option) between the Nginx configuration file
# and the enabled sites directory
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart Nginx
service nginx start
# terminates the first nginx ID
kill "$(pgrep 'nginx' | head -1)"
